# Generated by Django 5.0 on 2025-06-06 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0004_telegrambotuser_openai_thread_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('amount_credits', models.PositiveIntegerField(verbose_name='Amount Credits')),
                ('features', models.TextField(verbose_name='Features')),
                ('discount', models.PositiveIntegerField(verbose_name='Discount')),
            ],
            options={
                'verbose_name': 'Payment Plan',
                'verbose_name_plural': 'Payment Plans',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thread_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Thread ID')),
                ('run_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Run ID')),
                ('telegram_message_id', models.CharField(max_length=100, null=True, verbose_name='Telegram Message ID')),
                ('input_message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('input_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='File')),
                ('response_message', models.TextField(blank=True, null=True, verbose_name='Response Message')),
                ('cost', models.PositiveIntegerField(default=50, verbose_name='Cost')),
                ('is_on_process', models.BooleanField(default=False, verbose_name='On Process')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Finished')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.telegramuser')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('total_credits', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Credits')),
                ('status', models.CharField(default='success', max_length=10, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.paymentplan', verbose_name='Plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.telegramuser', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
