# Generated by Django 5.0 on 2025-06-06 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='PaymentPlan',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
