# Generated by Django 5.2.1 on 2025-05-27 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name')),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='Phone Number')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('language', models.CharField(blank=True, choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], db_index=True, max_length=255, null=True, verbose_name='Language')),
                ('number_of_referals', models.PositiveIntegerField(default=0, verbose_name='Number of Referals')),
                ('registred_date', models.DateTimeField(blank=True, null=True, verbose_name='Registred Date')),
                ('referal_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.telegramuser')),
            ],
            options={
                'verbose_name': 'Telegram User',
                'verbose_name_plural': 'Telegram Users',
            },
        ),
        migrations.CreateModel(
            name='TelegramBotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.CharField(db_index=True, max_length=255, verbose_name='Bot')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.telegramuser', verbose_name='Telegram User')),
            ],
            options={
                'verbose_name': 'Telegram Bot User',
                'verbose_name_plural': 'Telegram Bot Users',
            },
        ),
    ]
