# Generated by Django 5.2.1 on 2025-05-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='balance',
            field=models.PositiveIntegerField(default=0, verbose_name='Balance'),
        ),
    ]
