# Generated by Django 5.2.1 on 2025-05-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_telegramuser_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='balance',
            field=models.PositiveIntegerField(default=300, verbose_name='Balance'),
        ),
    ]
