# Generated by Django 5.2.1 on 2025-06-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_telegramuser_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambotuser',
            name='openai_thread_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='OpenAI Thread ID'),
        ),
    ]
